### PR TITLE
fix lifetime for Muncher::text()

### PR DESCRIPTION
**Pull request by chris-laplante**
Signed-off-by: Chris Laplante <chris.laplante@agilent.com>

### CODE REVIEW

**Comment by DevinR528** [comment]
Thanks for the catch!

**Comment by chris-laplante** [comment]
Sure thing, thanks for the library :). It's very useful to me.

**Comment by DevinR528** [comment]
What have you been using it for (just curious).

**Comment by chris-laplante** [comment]
> What have you been using it for (just curious).

To write a lexer for the BitBake language (https://www.yoctoproject.org/docs/latest/bitbake-user-manual/bitbake-user-manual.html#bitbake-user-manual-metadata)

**Comment by DevinR528** [comment]
Cool!!

**Pull request merged**
