### PR TITLE
bump version to 0.6.2

### PR DESCRIPTION
**Pull request by chris-laplante**

### CODE REVIEW

**Comment by DevinR528** [comment]
Ugh duh, "hint hint you should have made a release for this breaking change too" sorry.
Thanks for the reminder! :facepalm: 

Released to crates.io

**Comment by chris-laplante** [comment]
no problem :). I will be releasing our code on GitHub here soon so just wanted to make sure this was squared away.

**Comment by DevinR528** [comment]
Sweet let me know so I can check it out!

**Comment by chris-laplante** [comment]
will do!

**Pull request merged**
